[tool.poetry]
name = "dishook"
version = "0.1.0"
description = ""
authors = ["dafty144 <contact@leojohnston.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
